import Link from "next/link";
import { ArrowLeft, CalendarDays, CreditCard, MapPin, Phone } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { ClientDetailsActions } from "@/features/clients/ui/client-details-actions";
import { Card, CardContent } from "@/components/ui/card";
import { AdminAccessDeniedError, requireActiveAdmin } from "@/features/auth/application/require-active-admin";
import { ClientsRepository } from "@/features/clients/infrastructure/clients-repository";
import { listPackages } from "@/features/packages/application/list-packages";
import { formatFcfa } from "@/shared/format-fcfa";
import { PaymentsRepository } from "@/features/payments/infrastructure/payments-repository";
import { PaymentActions } from "@/features/payments/ui/payment-actions";
import { SubscriptionsRepository } from "@/features/subscriptions/infrastructure/subscriptions-repository";
import { getNextDueDate, getPaymentProgress, getPaymentTotals } from "@/features/payments/domain/payment-status";
import { getClientDueStatus } from "@/features/payments/domain/payment-due";
import { ClientFinanceBadge } from "@/features/clients/ui/client-finance-badge";

export const dynamic = "force-dynamic";

export default async function ClientDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  try { await requireActiveAdmin(); } catch (error) {
    if (error instanceof AdminAccessDeniedError) redirect("/login");
    redirect("/clients");
  }
  const clientId = (await params).id;
  const [client, packages] = await Promise.all([new ClientsRepository().findById(clientId), listPackages()]);
  if (!client) notFound();
  const payments = await new PaymentsRepository().listByClient(client.id);
  const subscriptions = await new SubscriptionsRepository().listByClient(client.id);
  const { paidAmount, remainingAmount, status } = getPaymentTotals(client.totalAmount, payments);
  const progress = getPaymentProgress(client.durationMonths, client.monthlyAmount, paidAmount);
  const nextDueDate = getNextDueDate(client.subscriptionDate, progress.completedMonths);
  const due = getClientDueStatus(client, paidAmount);
  const subscriptionDate = new Intl.DateTimeFormat("fr-FR").format(new Date(`${client.subscriptionDate}T00:00:00`));
  const formattedNextDueDate = new Intl.DateTimeFormat("fr-FR").format(new Date(`${nextDueDate}T00:00:00`));
  const initials = client.name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();

  return <main className="min-h-dvh bg-slate-100"><div className="mx-auto max-w-7xl space-y-6 px-5 py-7 sm:px-8 lg:px-10">
    <Link href="/clients" className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 transition hover:text-blue-700"><ArrowLeft size={16} aria-hidden="true" /> Clients</Link>
    <header className="flex flex-col gap-5 border-b border-slate-200 pb-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-blue-100 text-lg font-bold text-blue-800">{initials}</div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-700">Fiche client</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">{client.name}</h1><p className="mt-1 text-sm text-slate-500">{client.code}</p></div></div><div className="flex items-center gap-3"><ClientFinanceBadge status={status} /><ClientDetailsActions client={client} packages={packages} /></div></header>
    <div className="grid gap-4 sm:grid-cols-4"><Card className="rounded-xl border-slate-200 shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Contractuel</p><p className="mt-2 text-xl font-bold text-slate-950">{formatFcfa(client.totalAmount)}</p></CardContent></Card><Card className="rounded-xl border-slate-200 shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Payé</p><p className="mt-2 text-xl font-bold text-emerald-700">{formatFcfa(paidAmount)}</p></CardContent></Card><Card className="rounded-xl border-slate-200 shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Reste à payer</p><p className="mt-2 text-xl font-bold text-red-700">{formatFcfa(remainingAmount)}</p></CardContent></Card><Card className="rounded-xl border-slate-200 shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Échéance</p><p className={`mt-2 text-xl font-bold ${due.dueStatus === "overdue" ? "text-red-700" : due.dueStatus === "complete" ? "text-slate-400" : "text-amber-700"}`}>{due.dueStatus === "complete" ? "Terminé" : due.dueStatus === "overdue" ? "En retard" : "À venir"}</p><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat("fr-FR").format(new Date(`${nextDueDate}T00:00:00`))}</p></CardContent></Card></div>
    <div className="grid gap-6 lg:grid-cols-[1fr_1.4fr]"><section aria-labelledby="identity-title" className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 id="identity-title" className="font-bold text-slate-950">Informations personnelles</h2></div><dl className="divide-y divide-slate-100"><div className="flex items-center gap-3 px-5 py-4"><Phone size={17} className="text-slate-400" aria-hidden="true" /><div><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">Téléphone</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{client.phone}</dd></div></div><div className="flex items-center gap-3 px-5 py-4"><MapPin size={17} className="text-slate-400" aria-hidden="true" /><div><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">Localisation</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{client.location}</dd></div></div></dl></section><section aria-labelledby="subscription-title" className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center gap-2 border-b border-slate-200 px-5 py-4"><CreditCard size={17} className="text-blue-700" aria-hidden="true" /><h2 id="subscription-title" className="font-bold text-slate-950">Détails de l’abonnement</h2></div><div className="grid gap-x-8 gap-y-5 p-5 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Forfait souscrit</p><p className="mt-1 text-sm font-semibold text-slate-700">{client.packageName}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Date de début</p><p className="mt-1 flex items-center gap-2 text-sm font-semibold text-slate-700"><CalendarDays size={15} className="text-slate-400" aria-hidden="true" />{subscriptionDate}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Durée</p><p className="mt-1 text-sm font-semibold text-slate-700">{client.durationMonths} mois</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Mensualité</p><p className="mt-1 text-sm font-semibold text-slate-700">{formatFcfa(client.monthlyAmount)}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Prochaine échéance</p><p className="mt-1 text-sm font-semibold text-slate-700">{formattedNextDueDate}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Mensualités restantes</p><p className="mt-1 text-sm font-semibold text-slate-700">{progress.remainingMonths.toString()}</p></div></div></section></div>
    <section aria-labelledby="subscriptions-title" className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 id="subscriptions-title" className="font-bold text-slate-950">Historique des abonnements</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-bold">Période</th><th className="px-5 py-3 font-bold">Forfait</th><th className="px-5 py-3 font-bold">Durée</th><th className="px-5 py-3 font-bold">Montant</th><th className="px-5 py-3 font-bold">Statut</th></tr></thead><tbody className="divide-y divide-slate-100">{(subscriptions.length ? subscriptions : [{ id: "current", subscriptionDate: client.subscriptionDate, packageName: client.packageName, durationMonths: client.durationMonths, totalAmount: client.totalAmount, endedAt: undefined }]).map((subscription) => <tr key={subscription.id}><td className="px-5 py-4 text-slate-600">{new Intl.DateTimeFormat("fr-FR").format(new Date(`${subscription.subscriptionDate}T00:00:00`))}</td><td className="px-5 py-4 font-semibold text-slate-950">{subscription.packageName}</td><td className="px-5 py-4 text-slate-600">{subscription.durationMonths} mois</td><td className="px-5 py-4 font-semibold text-slate-950">{formatFcfa(subscription.totalAmount)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${subscription.endedAt ? "bg-slate-100 text-slate-600" : "bg-blue-50 text-blue-700"}`}>{subscription.endedAt ? "Terminé" : "En cours"}</span></td></tr>)}</tbody></table></div></section>
    <section aria-labelledby="payments-title" className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="payments-title" className="font-bold text-slate-950">Historique des paiements</h2><p className="mt-1 text-xs text-slate-500">Total encaissé : <span className="font-semibold text-slate-700">{formatFcfa(paidAmount)}</span></p></div><PaymentActions clientId={client.id} /></div>{payments.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-bold">Date</th><th className="px-5 py-3 font-bold">Montant</th><th className="px-5 py-3 font-bold">Mode</th><th className="px-5 py-3 font-bold">Référence</th><th className="px-5 py-3 font-bold">Observation</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.map((payment) => <tr key={payment.id}><td className="px-5 py-4 text-slate-600">{new Intl.DateTimeFormat("fr-FR").format(new Date(`${payment.date}T00:00:00`))}</td><td className="px-5 py-4 font-semibold text-slate-950">{formatFcfa(payment.amount)}</td><td className="px-5 py-4 text-slate-600">{payment.method}</td><td className="px-5 py-4 text-slate-600">{payment.reference || "-"}</td><td className="px-5 py-4 text-slate-600">{payment.note || "-"}</td></tr>)}</tbody></table></div> : <div className="px-5 py-10 text-center"><p className="text-sm font-semibold text-slate-700">Aucun paiement enregistré</p><p className="mt-1 text-sm text-slate-500">Les transactions de ce client apparaîtront ici.</p></div>}</section>
    {client.notes && <section aria-labelledby="notes-title" className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 id="notes-title" className="font-bold text-slate-950">Notes</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{client.notes}</p></section>}
  </div></main>;
}
